FROM public.ecr.aws/bitnami/node:18.9.0 AS build
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn
COPY . .
RUN yarn build product

FROM public.ecr.aws/bitnami/node:18.0.0
WORKDIR /app
COPY --from=build /app ./
EXPOSE 3005
CMD ["npm", "run", "start:product"]
