apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-application
  template:
    metadata:
      labels:
        app: admin-application
    spec:
      containers:
        - name: admin-application
          image: ADMIN_APPLICATION_ECR:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-application-service
spec:
  selector:
    app: admin-application
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-application-service-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: ELB_URL
      http:
        paths:
          - backend:
              service:
                name: admin-application-service
                port:
                  number: 80
            path: /admin
            pathType: Prefix
